# Generated by Django 5.2.4 on 2026-02-03 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
