# Generated by Django 5.2.4 on 2026-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0002_sensor_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='board_type',
            field=models.CharField(choices=[('esp32', 'ESP32'), ('esp32c3_supermini', 'ESP32-C3 SuperMini')], default='esp32', max_length=50),
        ),
    ]
