# Generated by Django 5.2.4 on 2026-02-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0003_sensor_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_fields',
            field=models.CharField(default='temperature', help_text='Comma-separated list of expected fields (e.g., temperature,humidity)', max_length=255),
        ),
    ]
