# Generated by Django 5.2.4 on 2026-02-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0004_sensor_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='attached_sensor',
            field=models.CharField(choices=[('custom', 'Custom / Other'), ('dht11', 'DHT11 (Temp & Humidity)')], default='custom', max_length=50),
        ),
    ]
