# Generated by Django 5.2.4 on 2026-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0005_sensor_attached_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latest_data',
            field=models.TextField(default='{}', help_text='Latest data received from the sensor (JSON format)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='attached_sensor',
            field=models.CharField(choices=[('custom', 'Custom / Other'), ('dht11', 'DHT11 (Temp & Humidity)'), ('timer', 'Timer (Start, End, Current, Elapsed, Left)')], default='custom', max_length=50),
        ),
    ]
