# Generated by Django 5.2.4 on 2026-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0006_sensor_latest_data_alter_sensor_attached_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='attached_sensor',
            field=models.CharField(choices=[('custom', 'Custom / Other'), ('dht11', 'DHT11 (Temp & Humidity)'), ('timer', 'Timer (Start, End, Current, Elapsed, Left)'), ('MPU6050_vib', 'MPU6050 Vibration (x, y, z)')], default='custom', max_length=50),
        ),
    ]
