# Generated by Django 5.2.4 on 2026-04-09 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0008_alter_sensor_attached_sensor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='API 키'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='attached_sensor',
            field=models.CharField(choices=[('custom', '사용자 정의 / 기타'), ('dht11', 'DHT11 (온도 및 습도)'), ('timer', '타이머 (시작, 종료, 현재, 경과, 남은 시간)'), ('MPU6050_vib', 'MPU6050 진동 (x, y, z)'), ('bme280', 'BME280 (온도, 습도, 기압)'), ('bh1750', 'BH1750 (조도)')], default='custom', max_length=50, verbose_name='연결된 센서'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='board_type',
            field=models.CharField(choices=[('esp32', 'ESP32'), ('esp32c3_supermini', 'ESP32-C3 SuperMini'), ('arduino_esp01', 'Arduino with ESP-01')], default='esp32', max_length=50, verbose_name='보드 종류'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 일시'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_fields',
            field=models.CharField(default='temperature', help_text='수집할 데이터 필드 목록 (쉼표로 구분, 예: temperature,humidity)', max_length=255, verbose_name='데이터 필드'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latest_data',
            field=models.TextField(default='{}', help_text='센서로부터 수신된 최신 데이터 (JSON 형식)', verbose_name='최신 수집 데이터'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measurement_name',
            field=models.CharField(help_text='InfluxDB에서 사용될 측정 항목 이름 (예: IoT_Edu_Float)', max_length=100, verbose_name='데이터 식별자 (Measurement)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='센서 이름'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL, verbose_name='소유자'),
        ),
    ]
