# Generated by Django 5.2.4 on 2026-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0010_alter_sensor_attached_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='attached_sensor',
            field=models.CharField(choices=[('custom', '사용자 정의 / 기타'), ('dht11', 'DHT11 (온도 및 습도)'), ('timer', '타이머 (시작, 종료, 현재, 경과, 남은 시간)'), ('MPU6050_vib', 'MPU6050 진동 (x, y, z)'), ('bme280', 'BME280 (온도, 습도, 기압)'), ('bh1750', 'BH1750 (조도)'), ('aht10', 'AHT10 (온도 및 습도)'), ('mSensor01', '복합 센서 (Vib, Temp, Hum, Sound)')], default='custom', max_length=50, verbose_name='연결된 센서'),
        ),
    ]
