# Generated by Django 5.2.4 on 2026-07-03 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0011_alter_sensor_attached_sensor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='LLM 서버 이름')),
                ('url', models.URLField(help_text='OpenAI 호환 API 엔드포인트 (예: http://192.168.0.100:11434/v1)', max_length=500, verbose_name='서버 URL')),
                ('api_key', models.CharField(blank=True, help_text='필요한 경우 API 키 입력 (Ollama는 비워둠)', max_length=500, verbose_name='API 키')),
                ('default_model', models.CharField(default='gemma3:12b', max_length=100, verbose_name='기본 모델')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM 서버',
                'verbose_name_plural': 'LLM 서버 목록',
            },
        ),
    ]
