# Generated by Django 5.2.4 on 2026-07-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_iot', '0012_llmserver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='', verbose_name='분석 주의사항')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='great_iot.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 분석 설정',
                'verbose_name_plural': 'AI 분석 설정 목록',
                'unique_together': {('user', 'sensor')},
            },
        ),
    ]
